
    create table big_job (
        active boolean not null,
        cooldown numeric(21,0),
        duration numeric(21,0),
        id bigint generated by default as identity,
        last_taken timestamp(6) with time zone,
        start_time timestamp(6) with time zone,
        primary key (id)
    );

    create table block_info (
        id bigint generated by default as identity,
        reporter_id bigint unique,
        user_id bigint unique,
        reason varchar(255),
        primary key (id)
    );

    create table capybara (
        deleted boolean not null,
        chat_id bigint,
        created timestamp(6),
        currency bigint,
        fight_id bigint unique,
        happiness_id bigint unique,
        id bigint generated by default as identity,
        improvement_id bigint unique,
        level_id bigint unique,
        photo_id bigint unique,
        preparation_id bigint unique,
        race_id bigint unique,
        race_request_id bigint unique,
        satiety_id bigint unique,
        spouse_id bigint unique,
        tea_id bigint unique,
        user_id bigint,
        wedding_gift_id bigint unique,
        work_id bigint unique,
        name varchar(255),
        primary key (id)
    );

    create table chat (
        id bigint not null,
        name varchar(255),
        primary key (id)
    );

    create table chat_users (
        chat_id bigint not null,
        users_id bigint not null,
        primary key (chat_id, users_id)
    );

    create table fight (
        cooldown numeric(21,0),
        loses integer not null,
        wins integer not null,
        id bigint generated by default as identity,
        last_fight timestamp(6),
        heal varchar(255) check ((heal in ('NONE','HEALING_HERB','ANTI_DEBUFFS'))),
        shield varchar(255) check ((shield in ('NONE','SHIELD_LEAF','BLADE_MALE'))),
        special varchar(255) check ((special in ('NONE','AEGIS'))),
        weapon varchar(255) check ((weapon in ('NONE','FIRE_CARROT','DAGGER','CAPYBARA_SWORD'))),
        primary key (id)
    );

    create table happiness (
        level integer,
        id bigint generated by default as identity,
        last_happy timestamp(6),
        primary key (id)
    );

    create table improvement (
        level integer,
        id bigint generated by default as identity,
        last_time timestamp(6),
        next_time timestamp(6),
        improvement_value varchar(255) check ((improvement_value in ('BOOTS','WATERMELON','ANTI_LOSE','NONE'))),
        primary key (id)
    );

    create table level (
        value integer,
        id bigint generated by default as identity,
        type varchar(255) check ((type in ('COMMON','FUNNY','COOL','INCREDIBLE','ROYAL','MAGICAL','PLANETARY','COSMIC','INTERGALACTIC','UNIVERSAL','SPACE_TIME','CAPY_GOD'))),
        primary key (id)
    );

    create table photo (
        type smallint check ((type between 0 and 1)),
        file_size bigint,
        id bigint generated by default as identity,
        file_id varchar(255),
        file_unique_id varchar(255),
        url varchar(255),
        primary key (id)
    );

    create table preparation (
        level integer,
        id bigint generated by default as identity,
        last_time timestamp(6),
        next_time timestamp(6),
        primary key (id)
    );

    create table race (
        charges integer,
        max_charges integer,
        defeats bigint not null,
        id bigint generated by default as identity,
        last_spent timestamp(6),
        wins bigint not null,
        primary key (id)
    );

    create table race_request (
        challenger_id bigint unique,
        created_at timestamp(6),
        id bigint generated by default as identity,
        opponent_id bigint unique,
        status varchar(255) check ((status in ('PENDING','ACCEPTED','DECLINED'))),
        primary key (id)
    );

    create table satiety (
        level integer,
        id bigint generated by default as identity,
        last_fed timestamp(6),
        primary key (id)
    );

    create table tea (
        is_waiting boolean not null,
        id bigint generated by default as identity,
        last_tea timestamp(6),
        primary key (id)
    );

    create table usr (
        blocked boolean not null,
        created_at timestamp(6),
        id bigint not null,
        last_time_updated_at timestamp(6),
        blocked_reason varchar(255),
        user_role varchar(255) check ((user_role in ('SUPER_ADMIN','USER','ADMIN'))),
        username varchar(255),
        primary key (id)
    );

    create table usr_chats (
        chats_id bigint not null,
        user_id bigint not null,
        primary key (chats_id, user_id)
    );

    create table wedding_requests (
        created_at timestamp(6),
        id bigint generated by default as identity,
        proposer_id bigint unique,
        target_id bigint unique,
        status varchar(255) check ((status in ('PENDING','ACCEPTED','DECLINED'))),
        type varchar(255) check ((type in ('WEDDING','UNWEDDING'))),
        primary key (id)
    );

    create table wedding_gift (
        amount integer,
        id bigint generated by default as identity,
        last_time timestamp(6),
        primary key (id)
    );

    create table work (
        cooldown numeric(21,0),
        duration numeric(21,0),
        index integer,
        rise integer,
        big_job_id bigint unique,
        id bigint generated by default as identity,
        last_taken timestamp(6) with time zone,
        start_time timestamp(6) with time zone,
        work_type varchar(255) check ((work_type in ('NONE','IT','CASHIER','CRIMINAL'))),
        primary key (id)
    );

    create index idx_capybara_chat 
       on capybara (chat_id);

    create index idx_capybara_user 
       on capybara (user_id);

    create index idx_capybara_chat_user 
       on capybara (chat_id, user_id);

    alter table if exists block_info 
       add constraint FK89i32a98v8inmet9eiarr8y9h 
       foreign key (reporter_id) 
       references usr;

    alter table if exists block_info 
       add constraint FK4puwup95yx711a0ssudtepfg1 
       foreign key (user_id) 
       references usr;

    alter table if exists capybara 
       add constraint FK6vj0xui7dkvgmkbnkllfrfi85 
       foreign key (chat_id) 
       references chat;

    alter table if exists capybara 
       add constraint FKge8rnawmq051m0dvk3ubh3ps1 
       foreign key (fight_id) 
       references fight;

    alter table if exists capybara 
       add constraint FKfak5e31f2kts0aytqko47fybf 
       foreign key (happiness_id) 
       references happiness;

    alter table if exists capybara 
       add constraint FK191k3uvk20p3a403yv3uqxyon 
       foreign key (improvement_id) 
       references improvement;

    alter table if exists capybara 
       add constraint FK8ewk1kvc5fh4y3131bpixlpui 
       foreign key (level_id) 
       references level;

    alter table if exists capybara 
       add constraint FKac6urkbfkhyg8v0tdk49js60o 
       foreign key (photo_id) 
       references photo;

    alter table if exists capybara 
       add constraint FK9l6qdjwnxdk542331pwa0q86e 
       foreign key (preparation_id) 
       references preparation;

    alter table if exists capybara 
       add constraint FKifbbunxuepaa0l8w6fvsc8r94 
       foreign key (race_id) 
       references race;

    alter table if exists capybara 
       add constraint FKe4d7yct08vsanadf3nb8y22dm 
       foreign key (race_request_id) 
       references race_request;

    alter table if exists capybara 
       add constraint FK2cxekmeku15wenfj41r5hd32q 
       foreign key (satiety_id) 
       references satiety;

    alter table if exists capybara 
       add constraint FKo8jc90lhalywrc5ptlhvqgbhf 
       foreign key (spouse_id) 
       references capybara;

    alter table if exists capybara 
       add constraint FK3bpscsaaoinsqh8awcn8tm1c8 
       foreign key (tea_id) 
       references tea;

    alter table if exists capybara 
       add constraint FKc4ar6emr0drgblj1ikpuvpn30 
       foreign key (user_id) 
       references usr;

    alter table if exists capybara 
       add constraint FKbmf8likj96klsbec6f94hwepg 
       foreign key (wedding_gift_id) 
       references wedding_gift;

    alter table if exists capybara 
       add constraint FKk8jx05q0hhwpsjieh01axeebx 
       foreign key (work_id) 
       references work;

    alter table if exists chat_users 
       add constraint FKfktbvmu2c2m1nfktbll9g2489 
       foreign key (users_id) 
       references usr;

    alter table if exists chat_users 
       add constraint FKglok2i2m8cbulbt5xxmfqixw3 
       foreign key (chat_id) 
       references chat;

    alter table if exists race_request 
       add constraint FK6abmj9ct5qj5jul0txu7kgof8 
       foreign key (challenger_id) 
       references capybara;

    alter table if exists race_request 
       add constraint FK8aye8lwovo0dnuej5tl5j2vjq 
       foreign key (opponent_id) 
       references capybara;

    alter table if exists usr_chats 
       add constraint FKox06ati5vha2hyffp0arugrwy 
       foreign key (chats_id) 
       references chat;

    alter table if exists usr_chats 
       add constraint FK98lkwu1ove2qw8msjj16ra6lf 
       foreign key (user_id) 
       references usr;

    alter table if exists wedding_requests 
       add constraint FKkpcce1o08yy2wt71626eljmec 
       foreign key (proposer_id) 
       references capybara;

    alter table if exists wedding_requests 
       add constraint FK2ejk2e2eccesyxopgihdksjov 
       foreign key (target_id) 
       references capybara;

    alter table if exists work 
       add constraint FKd2rne95q5fa18a6jb10fpmwij 
       foreign key (big_job_id) 
       references big_job;
