server:
  port: 8080
spring:
  liquibase:
    enabled: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
#      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

telegram:
  mode: webhook
  token: ${BOT_TOKEN}
  admin-id: ${ADMIN_ID}
  bot-id: ${BOT_ID}
  webhook:
    url: ${WEBHOOK_URL}
    path: ${WEBHOOK_PATH}
  base-names:
    - messages/common/messages
    - messages/common/lists
    - messages/fight/messages
    - messages/admin/admin_messages
    - messages/casino/casino_messages
    - messages/work/work_messages
    - messages/race/messages
    - messages/info/info_messages

bot:
  photos:
    work:
      setter:
        cashier: https://vk.com/photo-209917797_457242285
        criminal: https://vk.com/photo-209917797_457242283
        it: https://vk.com/photo-209917797_457242284
      go-work:
        it-go-work: https://ru.dreamstime.com/%D0%BA%D0%B0%D0%BF%D0%B8%D0%B1%D0%B0%D1%80%D0%B0-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%D0%B5%D1%82-%D0%B7%D0%B0-%D0%BD%D0%BE%D1%83%D1%82%D0%B1%D1%83%D0%BA%D0%BE%D0%BC-%D0%B2-%D1%81%D0%BE%D0%B2%D1%80%D0%B5%D0%BC%D0%B5%D0%BD%D0%BD%D0%BE%D0%BC-%D0%B4%D0%BE%D0%BC%D0%B0%D1%88%D0%BD%D0%B5%D0%BC-%D0%BE%D1%84%D0%B8%D1%81%D0%B5-image429227255
        cashier-go-work: https://masterpiecer-images.s3.yandex.net/028d2544940711ee8b3ff6c574779d3e:upscaled
        criminal-go-work: https://masterpiecer-images.s3.yandex.net/05d24fa3704911ee91345696910b1137:upscaled
    feed: https://vk.com/photo-209917797_457245510
    fatten: https://vk.com/photo-209917797_457246187
    tea: https://vk.com/photo-209917797_457246193
    new-level: https://vk.com/photo-209917797_457246194
    new-type: https://vk.com/photo-209917797_457246195
    start: https://hi-news.ru/wp-content/uploads/2025/07/spokoimaya-kapibara-1-e1752078102391-750x523.jpg
    casino:
      win: https://vk.com/photo-209917797_457246197
      lose: https://vk.com/photo-209917797_457246192
      set-bet: https://vk.com/photo-209917797_457246196
    wedding: https://vk.com/photo-209917797_457245520
    fight:
      animation: https://thumbs.dreamstime.com/b/%D0%BF%D1%80%D0%B8%D0%BC%D0%B0%D0%BD%D0%BA%D0%B0-%D0%BA%D1%80%D0%BE%D0%BA%D0%BE-%D0%B8-%D0%B0-%D0%B0%D1%82%D0%B0%D0%BA%D1%83%D1%8F-75539401.jpg
    default-photos:
      - https://vk.com/photo-206143282_457239574
      - https://vk.com/photo-206143282_457239456
      - https://vk.com/photo-206143282_457239409
      - https://vk.com/photo-206143282_457239396
      - https://vk.com/photo-206143282_457239375
      - https://vk.com/photo-206143282_457239334
      - https://vk.com/photo-206143282_457239317
      - https://vk.com/photo-206143282_457239262
      - https://vk.com/photo-206143282_457239201
      - https://vk.com/photo-206143282_457239189
      - https://vk.com/photo-206143282_457239167
      - https://vk.com/photo-206143282_457239164
      - https://vk.com/photo-206143282_457239104
      - https://vk.com/photo-206143282_457239095
      - https://vk.com/photo-206143282_457239073
      - https://vk.com/photo-206143282_457239037
      - https://vk.com/photo-206143282_457239025
    race:
      improvement:
        boots: https://vk.com/photo-209917797_457246198
        watermelon: https://vk.com/photo-209917797_457246200
        anti-lose: https://vk.com/photo-209917797_457246201
      race-photos:
        - url: https://vk.com/photo-209917797_457241919
          type: PHOTO
        - url: https://vk.com/photo-209917797_457241924
          type: PHOTO
        - url: https://vk.com/photo-209917797_457241923
          type: PHOTO
        - url: https://vk.com/photo-209917797_457241922
          type: PHOTO
        - url: https://vk.com/photo-209917797_457241921
          type: PHOTO
        - url: https://vk.com/photo-209917797_457241920
          type: PHOTO
  #      - url: CgACAgQAAyEFAAS-gX0XAAIHtGjYEbh8dKraYQiUcwmSLVmUVDYfAAIVAwAC1nKsUYoLomnV0FyENgQ
  #        type: DOC
  #      - url: CgACAgQAAyEFAAS-gX0XAAIHtmjYEz6sNvRTpm6fxpdXTztLTgtZAAJ1AwACxpoFU0qXGu-MvYwDNgQ
  #        type: DOC
  #      - url: CgACAgQAAyEFAAS-gX0XAAIHt2jYE10Ytug2qfLFbZioVsSOFBMpAAL3AgAC-40MU9lbtg_EuWUxNgQ
  #        type: DOC